[package]
name = "tomat"
version = "0.1.0"
authors = ["Daniel Miller <danm1113@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
structopt = "0.2"

[dependencies.cursive]
version = "0.14"
features = ["toml"]
