# Every field in a theme file is optional.

# First come some various options
shadow = false  # Don't draw shadows around stacked views
borders = "simple"  # Alternatives are "none" and "outset"

# Here we define the color palette.
[colors]
background = "black"
shadow     = "black"
view       = "black"
primary   = "white"
secondary = "red"
tertiary  = "blue"
title_primary   = "red"
title_secondary = "magenta"
highlight          = "yellow"
highlight_inactive = "blue"
